Update start

diff --git a/start b/start
--- a/start
+++ b/start
@@ -21,8 +21,14 @@ pip3 install -U pip
 git clone $REPO_URL Github_Repo
 cd Github_Repo
 
-# Build Docker image
-docker build -t justcm .
+# Check if Dockerfile exists
+if [ -f "Dockerfile" ]; then
+    # Build Docker image
+    docker build -t justcm .
+else
+    echo "Error: Dockerfile not found in the repository."
+    exit 1
+fi
 
 # Run Docker container
 docker run justcm bash start.sh
